Update Jenkinsfile

diff --git a/DomainMonitoringSystemv1.0.4/Jenkinsfile b/DomainMonitoringSystemv1.0.4/Jenkinsfile
--- a/DomainMonitoringSystemv1.0.4/Jenkinsfile
+++ b/DomainMonitoringSystemv1.0.4/Jenkinsfile
@@ -1,11 +1,7 @@
-pipeline{
-    
-    // agent any
+pipeline {
     agent {
         label 'docker'
     }
-    
-//
 
     stages {
         stage('Clean Workspace') {
@@ -14,24 +10,24 @@ pipeline{
                     cleanWs()
                     echo "Workspace cleaned."
                     sh """
-                    sudo docker rm -f $(sudo docker ps -a -q)
+                    sudo docker rm -f \$(sudo docker ps -a -q)
                     """
                 }
                 echo "Docker containers removed."
             }
         }
 
-
-        stage('Clone repo') {
+        stage('Clone Repo') {
             steps {
                 script {
                     git branch: 'json-domain_baha', url: 'https://github.com/dorhs/project1.git'
                 }
             }
         }
-        stage('Docker build') {
+
+        stage('Docker Build') {
             steps {
-                dir('project1/DomainMonitoringSystemv1.0.4'){
+                dir('project1/DomainMonitoringSystemv1.0.4') {
                     script {
                         sh """
                         sudo docker build -t tpp:temp .
@@ -40,7 +36,8 @@ pipeline{
                 }
             }
         }
-        stage('Run container') {
+
+        stage('Run Container') {
             steps {
                 script {
                     sh """
@@ -50,5 +47,19 @@ pipeline{
             }
         }
     }
-    
+
+    post {
+        always {
+            echo "Build completed. Cleaning up Docker containers."
+            sh """
+            sudo docker rm -f \$(sudo docker ps -a -q) || true
+            """
+        }
+        failure {
+            echo "Pipeline failed!"
+        }
+        success {
+            echo "Pipeline succeeded!"
+        }
+    }
 }
